### ISSUE TITLE
probleme de sauvegarde html

### ISSUE THREAD

**Issue by marcus183** [subskybox/Orba#2]
hello i can t download on mac with chrome and theOrbaChordAndScaleEditor.html

**Comment by subskybox** [comment]
This is likely because your are trying this with a ._artipreset_ file (Orba 2) instead of of a ._orbapreset_ file (Orba 1). This code was developed for Orba 1 and does not work with Orba 2.

You can extract the values you need by opening the Chrome Developers Console:

> `<Command><Option>`J [Mac]

> `<Ctrl><Shift>`J [Windows]

and pasting in the following code followed by `<ENTER>`:
`console.log('<ChordModifierParams majorChordList="' + modifierDataArr.slice(50,82).map(function(_, i) {
            return i % 4 === 3 ? _ + '; ' : _ + ', ';
        }).join('').slice(0, -2) + '; " minorChordList="' + modifierDataArr.slice(82,114).map(function(_, i) {
            return i % 4 === 3 ? _ + '; ' : _ + ', ';
        }).join('').slice(0, -2) + '; "/>')`

This will give you the text to replace in your ._artipreset_ file.

**Comment by marcus183** [comment]
yes I replaced an artipreset file with orbapreset so everything works except the backup...:(
i do not programmation but i will try to find :)

**Comment by marcus183** [comment]
it s ok i find better solution for use my orba and very cool and beautifull song they have lot of music note usable..."https://www.youtube.com/watch?v=4t5pc_tFWrQ&list=PPSV" geoshred on ipad or iphone connect with orba
